#pragma once

#include "NativeGameplayTags.h"

// 행동 플래그
namespace HeistFlagTags
{
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Carrying);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_SoloCarrying);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_InFlashlight);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Disguised);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Panicked);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_HUDBlocked);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_Blinded);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag_OnSegway);
}
