#pragma once

#include "NativeGameplayTags.h"

namespace HeistAbilityTags
{
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sneak);
	
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_HelpCuffed);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_Kick);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_Heal);
	
	// Thief
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_PickUp);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_Drop);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_StartEngine);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_CloseDoor);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_Depart);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_LandMine);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_Disguise);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_PanicBucket);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Thief_PaintBomb);

	// Police
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Police_Attack);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Police_Cuffing);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Police_Escort);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Police_OpenDoor);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Police_Barricade);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Police_Flashbang);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Police_Grenade);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Police_Segway);

}
