#pragma once

#include "NativeGameplayTags.h"

namespace HeistStateTags
{
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sneaking);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ActionDisabled);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_MoveDisabled);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Channeling);
	
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Thief_Normal);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Thief_Injured);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Thief_Cuffed);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Thief_Escorted);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Thief_Out);

	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Police_Normal);
	HEIST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Police_Escorting);
}
